
name: Deploy iOS

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21 ' 
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle
      run: ./gradlew assembleXCFramework
    - name: Zip framework
      run: zip 'cryptokmplib.zip' '/Users/runner/work/crypto-kmp/crypto-kmp/cryptokmplib/build/XCFrameworks/release/cryptokmplib.xcframework'
    - name: Release to Github
      uses: softprops/action-gh-release@v1
      with:
        files: cryptokmplib.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Package.swift
      run: |
      $CHECKSUM_VAL=$(sha256sum "cryptokmplib.zip" | awk '{ print $1 }')
      ./createiOSPackage.sh Package-skeleton.swift Package.swift app_tag=${{ steps.vars.outputs.tag }} app_checksum=$CHECKSUM_VAL
