
name: Deploy iOS

on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle
      run: ./gradlew assembleXCFramework
    - name: Find build folder
      shell: bash
      run: |
       cp -a /Users/runner/work/crypto-kmp/crypto-kmp/cryptokmplib/build/XCFrameworks/release/. /Users/runner/work/crypto-kmp/crypto-kmp/distribution/
    - name: Commit add and push
      shell: bash
      run: |
        commit_message="XCFramevork commit"
        git add . -A
        git commit -m "$commit_message"
        git push
