
name: Deploy iOS

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
    runs-on: ${{ matrix.os }}
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.repository.default_branch }}
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21 ' 
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew assembleXCFramework
    - name: Zip framework
      run: |
       cd /Users/runner/work/crypto-kmp/crypto-kmp/cryptokmplib/build/XCFrameworks/release/
       zip -r 'cryptokmplib.zip' 'cryptokmplib.xcframework'
       cp cryptokmplib.zip /Users/runner/work/crypto-kmp/crypto-kmp/
    - name: Release to Github
      uses: softprops/action-gh-release@v1
      with:
        files: cryptokmplib.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Package.swift
      run: |
        echo "tag: "+${{  github.ref_name }}
        ./createiOSPackage.sh Package-skeleton.swift Package.swift app_tag=${{  github.ref_name }}
        rm -rf cryptokmplib.zip
    - name: Commit & Push changes
      run: |
        git status
        git config user.name 'globalid-bot'
        git config user.email 'github-bot[bot]@global.id'
        git commit -am "Generated Package.swift" || echo "There is nothing to commit"
        git push
